default:
     email_delivery:
        delivery_method: :smtp
        smtp_settings:
          tls: true
          address: "mailserver.example.com"
          port: 587
          authentication: :plain
          user_name: "nao-responda"
          password: "password"
