version: '3'

services:

  redmine:
    image: redmine:4.1
    networks:
      - redmine
    volumes:
      - ./data/volume:/var/redmine/files
    restart: always
    ports:
      - 8081:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: srvifs001
      REDMINE_SECRET_KEY_BASE: supersecretkey
      REDMINE_RELATIVE_URL_ROOT: /redmine
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    networks:
      - redmine
    volumes:
      - ./data/database:/var/redmine/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: srvifs001
      MYSQL_DATABASE: redmine

networks:
  redmine:
